/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RewardsRouteImport } from './routes/rewards'
import { Route as RecycleRouteImport } from './routes/recycle'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as CustomizerRouteImport } from './routes/customizer'
import { Route as IndexRouteImport } from './routes/index'

const RewardsRoute = RewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const RecycleRoute = RecycleRouteImport.update({
  id: '/recycle',
  path: '/recycle',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomizerRoute = CustomizerRouteImport.update({
  id: '/customizer',
  path: '/customizer',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/customizer': typeof CustomizerRoute
  '/profile': typeof ProfileRoute
  '/recycle': typeof RecycleRoute
  '/rewards': typeof RewardsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/customizer': typeof CustomizerRoute
  '/profile': typeof ProfileRoute
  '/recycle': typeof RecycleRoute
  '/rewards': typeof RewardsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/customizer': typeof CustomizerRoute
  '/profile': typeof ProfileRoute
  '/recycle': typeof RecycleRoute
  '/rewards': typeof RewardsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/customizer' | '/profile' | '/recycle' | '/rewards'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/customizer' | '/profile' | '/recycle' | '/rewards'
  id: '__root__' | '/' | '/customizer' | '/profile' | '/recycle' | '/rewards'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CustomizerRoute: typeof CustomizerRoute
  ProfileRoute: typeof ProfileRoute
  RecycleRoute: typeof RecycleRoute
  RewardsRoute: typeof RewardsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rewards': {
      id: '/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof RewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recycle': {
      id: '/recycle'
      path: '/recycle'
      fullPath: '/recycle'
      preLoaderRoute: typeof RecycleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customizer': {
      id: '/customizer'
      path: '/customizer'
      fullPath: '/customizer'
      preLoaderRoute: typeof CustomizerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CustomizerRoute: CustomizerRoute,
  ProfileRoute: ProfileRoute,
  RecycleRoute: RecycleRoute,
  RewardsRoute: RewardsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './D:/Downloads/goldstar reboot/goldstar reboot/src/router.tsx'
import type { startInstance } from './D:/Downloads/goldstar reboot/goldstar reboot/src/start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
